version: '3'

services:
  db:
    container_name: db_empleabilidad
    image: postgres:12.5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./dump_base.sql:/docker-entrypoint-initdb.d/dump_base.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - empleabilidad

  api:
    container_name: api_empleabilidad
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - empleabilidad

networks:
  empleabilidad: